name: Mind Your Stonks

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        openssl aes-256-cbc -K $encrypted_e21a95bd5d44_key -iv $encrypted_e21a95bd5d44_iv -in client_secret.json.enc -out client_secret.json -d
        pip install selenium
        wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
        mkdir geckodriver
        tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
        export PATH=$PATH:$PWD/geckodriver
        geckodriver --version || exit 1
        pip install gspread
        pip install --upgrade oauth2client
        pip install aenum
        pip install loguru
        pip install psutil
    - name: Install repo
      run: |
        pip install .
    - name: Read balance
      run: |
        query_balance.py $USERNAME $PASSWORD
      if: github.ref != 'refs/heads/master'
    - name: Publish sheets
      run: |
        query_balance.py $USERNAME $PASSWORD --update-spreadsheet ./client_secret.json
      if: github.ref == 'refs/heads/master'
